name: Scheduled Auto Update

on:
  schedule:
    # UTC时间13:45（北京时间21:45），使用新版cron表达式
    - cron: '45 13 * * *'
  workflow_dispatch:
    branches: [ main ]

jobs:
  auto-update:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 防止超时

    steps:
    # 最新版checkout配置
    - name: Checkout with PAT
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: true  # 必须开启才能推送

    # Python环境配置
    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'  # 自动缓存

    # 依赖安装优化
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 推荐使用文件管理

    # 主脚本执行
    - name: Execute update script
      run: python main.py
      env:
        TZ: Asia/Shanghai  # 脚本内时间控制

    # 智能提交优化
    - name: Commit & Push Changes
      if: always()  # 即使脚本失败也尝试提交
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        # 更可靠的文件变化检测
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "AutoUpdate: $(date +'%Y-%m-%d %H:%M:%S')"
          git pull --rebase  # 防止冲突
          git push origin main
          echo "Changes pushed successfully."
        else
          echo "No changes to commit."
        fi
