name: Daily Update

on:
  schedule:
    # Adjust cron for UTC time (21:45 Asia/Shanghai = 13:45 UTC)
    - cron: '45 13 * * *'
  workflow_dispatch:
    branches: [main]

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: true  # Allows subsequent git push

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run Python script
      run: python main.py

    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git checkout main
        git add -A
        # Check if there are changes to commit
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Auto-update live files"
          git push
        fi

    env:
      TZ: Asia/Shanghai
